# fly.toml app configuration file generated for vlas-intake on 2025-07-25T18:53:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vlas-intake'
primary_region = 'iad'

[build]

[http_service]
internal_port = 8765
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[env]
DOMAIN = 'vlas-intake.fly.dev'
PROTOCOL = 'https'
LOG_LEVEL = 'DEBUG'
FETCH_URL = 'https://lemma-intake.fly.dev/api/classify'
LEGAL_SERVER_SUBDOMAIN = 'vlas-demo'
TRANSFORMERS_NO_ADVISORY_WARNINGS = '1'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
