[project]
name = "intake-bot"
version = "0.1.4"
description = "Virginia Legal Aid Society (VLAS) Telephone Intake Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "granian",
    "loguru",
    "phonenumberslite",
    "pipecat-ai-flows",
    "pipecat-ai[openai,google,local-smart-turn-v3,websocket]",
    "python-dotenv",
    "python-multipart",
    "pyyaml",
    "rapidfuzz",
    "twilio",
    "winuvloop>=0.2.0",
]

[dependency-groups]
dev = ["granian[reload]", "pipecat-ai-tail", "pipecat-ai-whisker", "pytest-asyncio", "pytest"]
test = ["pytest-asyncio", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
intake_bot = ["data/*.yml"]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
pythonpath = ["src"]
required_plugins = ["pytest-asyncio"]
filterwarnings = ["ignore::DeprecationWarning:pipecat"]
