[project]
name = "intake-bot"
version = "0.1.2"
description = "Virginia Legal Aid Society (VLAS) Telephone Intake Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles",
    "anthropic>=0.66.0",
    "fastapi",
    "granian",
    "loguru",
    "numba",
    "onnxruntime",
    "phonenumberslite",
    "pipecat-ai-flows",
    "pipecat-ai-whisker",
    "pipecat-ai[openai,google,websocket]",
    "python-dotenv",
    "python-multipart",
    "pyyaml",
    "rapidfuzz",
    "twilio",
    "winuvloop>=0.2.0",
]

[dependency-groups]
dev = ["granian[reload]", "pytest-asyncio", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
asbar = ["__assets__/*.xml"]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
pythonpath = ["src"]
required_plugins = ["pytest-asyncio"]
filterwarnings = ["ignore::DeprecationWarning:pipecat"]
