[project]
name = "intake-bot"
version = "0.1.0"
description = "Virginia Legal Aid Society (VLAS) Telephone Intake Bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles",
    "fastapi",
    "loguru",
    "numba",
    "onnxruntime",
    "pipecat-ai-flows",
    "pipecat-ai[openai,google,websocket]",
    "python-dotenv",
    "python-multipart",
    "twilio",
    "uvicorn",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
intake-bot = "intake_bot.server:main"

[dependency-groups]
dev = ["pytest>=8.4.1", "pytest-asyncio>=1.1.0"]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
pythonpath = ["src"]
required_plugins = ["pytest-asyncio"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
asbar = ["__assets__/*.xml"]
