# Task: The Modern Task Runner. https://taskfile.dev/

version: "3"

silent: true

tasks:
  rundev:
    deps: [runserver, runclient, rundebug]

  runclient:
    cmds:
      - npm run --prefix ./client/typescript dev -- --clearScreen false --port 5173

  rundebug:
    cmds:
      - npm run --prefix ./debug/ui dev -- --clearScreen false --port 5174

  runserver:
    cmds:
      - granian intake_bot.server:app --interface asgi --host 0.0.0.0 --port 8765 --reload --reload-paths ./src/intake_bot
