version: '3'

tasks:
  rundev:
    deps: [runserver, runclient]

  runclient:
    cmds:
      - npm run --prefix ./client/typescript dev

  runserver:
    cmds:
      - granian intake_bot.server:app --interface asgi --host 0.0.0.0 --port 8765 --reload --reload-paths ./src/intake_bot
    silent: true
